# Mi primer cuaderno de trabajo

In [1]:
print("Hola mundo")
print("")

Hola mundo


# install numpy

In [1]:
pip install numpy

                                              0.0/15.0 MB ? eta -:--:--
                                              0.1/15.0 MB 3.3 MB/s eta 0:00:05
                                              0.2/15.0 MB 2.9 MB/s eta 0:00:06
     -                                        0.5/15.0 MB 3.9 MB/s eta 0:00:04
     -                                        0.7/15.0 MB 4.0 MB/s eta 0:00:04
     --                                       0.9/15.0 MB 4.3 MB/s eta 0:00:04
     ---                                      1.2/15.0 MB 4.3 MB/s eta 0:00:04
     ---                                      1.4/15.0 MB 4.4 MB/s eta 0:00:04
     ----                                     1.6/15.0 MB 4.5 MB/s eta 0:00:03
     ----                                     1.9/15.0 MB 4.6 MB/s eta 0:00:03
     -----                                    2.1/15.0 MB 4.6 MB/s eta 0:00:03
     -----                                    2.2/15.0 MB 4.7 MB/s eta 0:00:03
     ------                                   2.4/15.0 MB 4

# Numpy

In [3]:
import numpy as np

## Arreglos

In [4]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [5]:
arr = np.array(([1,2,3,],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
arr = np.array([1,2,3,4,5,6], ndmin=3)

print(arr.ndim)

print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

3
[[[1 2 3 4 5 6]]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
1


In [8]:
arr = np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [9]:
arr = np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


In [11]:
arr = np.random.rand(3,3)
print (arr)

[[0.09096471 0.18839022 0.04501853]
 [0.20172307 0.4436758  0.91488362]
 [0.58739797 0.78979865 0.85235182]]


## Operaciones

In [13]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.add(arr1, arr2)
print (arr3)

[5 7 9]


In [14]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.subtract(arr1, arr2)
print (arr3)

[-3 -3 -3]


In [15]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.multiply(arr1, arr2)
print (arr3)

[ 4 10 18]


In [16]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.divide(arr1, arr2)
print (arr3)

[0.25 0.4  0.5 ]


## Agregación

In [19]:
arr = [1,5,7]
media = np.mean(arr)
print(media)

4.333333333333333


In [21]:
arr = [1,5,7]
mediana = np.median(arr)
print(mediana)

5.0


In [22]:
arr = [1,5,7]
maximo = np.max(arr)
print(maximo)

7


In [23]:
arr = [1,5,7]
minimo = np.min(arr)
print(minimo)

1


## Indexación

In [25]:
arr = np.array([1,5,7])
print(arr[0])


1


In [26]:
arr = np.array([1,5,7])
print(arr[-1])


7


In [28]:
arr = np.array(([1,5,7],[1,2,3]))
print(arr[1,2])


3


## Slicing - Rangos

In [29]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:4])

[2 3 4]


In [31]:
arr = np.array([1,2,3,4,5,6,7,9,10])
print(arr[1:8:2])

[2 4 6 9]


In [32]:
arr = np.array([1,2,3,4,5,6,7,9,10])
print(arr[::2])

[ 1  3  5  7 10]
