# Mi primer cuaderno de trabajo

In [1]:
print("Hola mundo")
print("")

Hola mundo


# install numpy

In [1]:
pip install numpy

                                              0.0/15.0 MB ? eta -:--:--
                                              0.1/15.0 MB 3.3 MB/s eta 0:00:05
                                              0.2/15.0 MB 2.9 MB/s eta 0:00:06
     -                                        0.5/15.0 MB 3.9 MB/s eta 0:00:04
     -                                        0.7/15.0 MB 4.0 MB/s eta 0:00:04
     --                                       0.9/15.0 MB 4.3 MB/s eta 0:00:04
     ---                                      1.2/15.0 MB 4.3 MB/s eta 0:00:04
     ---                                      1.4/15.0 MB 4.4 MB/s eta 0:00:04
     ----                                     1.6/15.0 MB 4.5 MB/s eta 0:00:03
     ----                                     1.9/15.0 MB 4.6 MB/s eta 0:00:03
     -----                                    2.1/15.0 MB 4.6 MB/s eta 0:00:03
     -----                                    2.2/15.0 MB 4.7 MB/s eta 0:00:03
     ------                                   2.4/15.0 MB 4

# Numpy

In [3]:
import numpy as np

## Arreglos

In [4]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [5]:
arr = np.array(([1,2,3,],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
arr = np.array([1,2,3,4,5,6], ndmin=3)

print(arr.ndim)

print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

3
[[[1 2 3 4 5 6]]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
1


In [8]:
arr = np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [9]:
arr = np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


In [11]:
arr = np.random.rand(3,3)
print (arr)

[[0.09096471 0.18839022 0.04501853]
 [0.20172307 0.4436758  0.91488362]
 [0.58739797 0.78979865 0.85235182]]


## Operaciones

In [13]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.add(arr1, arr2)
print (arr3)

[5 7 9]


In [14]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.subtract(arr1, arr2)
print (arr3)

[-3 -3 -3]


In [15]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.multiply(arr1, arr2)
print (arr3)

[ 4 10 18]


In [16]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.divide(arr1, arr2)
print (arr3)

[0.25 0.4  0.5 ]


## Agregación

In [19]:
arr = [1,5,7]
media = np.mean(arr)
print(media)

4.333333333333333


In [21]:
arr = [1,5,7]
mediana = np.median(arr)
print(mediana)

5.0


In [22]:
arr = [1,5,7]
maximo = np.max(arr)
print(maximo)

7


In [23]:
arr = [1,5,7]
minimo = np.min(arr)
print(minimo)

1


## Indexación

In [25]:
arr = np.array([1,5,7])
print(arr[0])


1


In [26]:
arr = np.array([1,5,7])
print(arr[-1])


7


In [28]:
arr = np.array(([1,5,7],[1,2,3]))
print(arr[1,2])


3


## Slicing - Rangos

In [29]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:4])

[2 3 4]


In [31]:
arr = np.array([1,2,3,4,5,6,7,9,10])
print(arr[1:8:2])

[2 4 6 9]


In [32]:
arr = np.array([1,2,3,4,5,6,7,9,10])
print(arr[::2])

[ 1  3  5  7 10]


## Tipos de datos

In [3]:
import numpy as np
arr = np.array(["b", "a"])
print (arr)
print (arr.dtype)

['b' 'a']
<U1


In [4]:
import numpy as np
arr = np.array([1.1, 2.3])
print (arr)
print (arr.dtype)

[1.1 2.3]
float64


In [7]:
# 'i' = integer
# 'b' = booleano
# 'f' = flotante
# 'M' = datatime
# 'O' = objeto
# 'S' 0 string

arr = np.array([1,2,3], dtype='S')

print (arr)

[b'1' b'2' b'3']


In [9]:
#Arreglo Flotante
arr = np.array([1.1,2.2,3.3])
print("pre", arr)
print(arr.dtype)

#Se asigna arreglo flotante a un nuevo arreglo integer
nuevo_arr = arr.astype('i')
print("post", nuevo_arr)
print(nuevo_arr.dtype)

pre [1.1 2.2 3.3]
float64
post [1 2 3]
int32


In [ ]:
## Copy vs view
#### copy --> Guarda los valores de la instancia original
#### view --> Vista del arreglo en tiempo real

In [10]:
arr = np.array([1,2,3])

x = arr.copy()
y = arr.view()

print("arreglo", arr)
print("x", x)
print("y", y)

arr[0] = 0

print("arreglo", arr)
print("x", x)
print("y", y)



arreglo [1 2 3]
x [1 2 3]
y [1 2 3]
arreglo [0 2 3]
x [1 2 3]
y [0 2 3]


## Concatenar

In [11]:
arr1 = np.array([1,2,3])
print(arr1)

arr2 = np.array([4,5,6])
print(arr2)

arr3 = np.concatenate((arr1,arr2))
print(arr3)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


## Busqueda

In [12]:
arr = np.array([1,2,3,4,5,5,6])
x = np.where(arr == 5)
print(x)


(array([4, 5], dtype=int64),)


## Ordenar

In [13]:
arr = np.array([9,2,7,4,5,5,6])
# ordenar arreglo
x = np.sort(arr)
print (x)

[2 4 5 5 6 7 9]


# Pandas

In [14]:
pip install pandas

                                              0.0/10.6 MB ? eta -:--:--
                                              0.1/10.6 MB 2.0 MB/s eta 0:00:06
                                              0.1/10.6 MB 1.8 MB/s eta 0:00:06
     -                                        0.5/10.6 MB 3.5 MB/s eta 0:00:03
     --                                       0.6/10.6 MB 3.6 MB/s eta 0:00:03
     --                                       0.7/10.6 MB 3.1 MB/s eta 0:00:04
     ---                                      0.9/10.6 MB 3.3 MB/s eta 0:00:03
     ---                                      1.0/10.6 MB 3.2 MB/s eta 0:00:04
     ----                                     1.1/10.6 MB 3.0 MB/s eta 0:00:04
     ----                                     1.2/10.6 MB 2.9 MB/s eta 0:00:04
     ----                                     1.3/10.6 MB 2.9 MB/s eta 0:00:04
     -----                                    1.4/10.6 MB 2.7 MB/s eta 0:00:04
     -----                                    1.4/10.6 MB 2

In [36]:
import pandas as pd

## Series

In [19]:
a = np.array([9,8,7])
srs = pd.Series(a)
print(srs)

# Se asignan valores a los indices
srs = pd.Series(a, index = ["x","y","z"])
print(srs)
print (srs["x"])

0    9
1    8
2    7
dtype: int32
x    9
y    8
z    7
dtype: int32
9


In [20]:
pasos = {
    "lunes" : 440,
    "martes" : 620,
    "miercoles" : 700,
    "jueves" : 500,
    "viernes" : 150
}

srs = pd.Series(pasos)
print(srs)

lunes        440
martes       620
miercoles    700
jueves       500
viernes      150
dtype: int64


In [21]:
#Filtrar por indice
srs = pd.Series(pasos, index = ["lunes", "viernes"])
print(srs)

lunes      440
viernes    150
dtype: int64


## Dataframe

In [22]:
mydataset =  {
    'operador': ["John Doe", "Sr. X", "Lorem ipsum"],
    'no. reloj': [101,202,303]
}

df = pd.DataFrame(mydataset)
print(df)

      operador  no. reloj
0     John Doe        101
1        Sr. X        202
2  Lorem ipsum        303


In [23]:
df['no. reloj']

0    101
1    202
2    303
Name: no. reloj, dtype: int64

In [24]:
df[df['no. reloj'] > 101]

operador  no. reloj
1        Sr. X        202
2  Lorem ipsum        303

In [26]:
#Crear una nueva columna al dataframe
df['asistencia'] = [True, False, True]
print(df)

      operador  no. reloj  asistencia
0     John Doe        101        True
1        Sr. X        202       False
2  Lorem ipsum        303        True


In [27]:
print(df.loc[0])

operador      John Doe
no. reloj          101
asistencia        True
Name: 0, dtype: object


In [29]:
print(df.loc[[0,1]])

   operador  no. reloj  asistencia
0  John Doe        101        True
1     Sr. X        202       False


In [31]:
df = pd.DataFrame(mydataset, index=["CEO", "COO", "CFP"])
print(df)

        operador  no. reloj
CEO     John Doe        101
COO        Sr. X        202
CFP  Lorem ipsum        303


In [32]:
print(df.loc["CEO"])

operador     John Doe
no. reloj         101
Name: CEO, dtype: object


## Vistas

In [41]:
df = pd.read_csv("dataset/Perfil de estudiante.csv")

df

Marca temporal  \
0    2023/06/27 7:42:12 p. m. GMT-6   
1    2023/06/27 7:42:28 p. m. GMT-6   
2    2023/06/27 7:42:44 p. m. GMT-6   
3    2023/06/27 7:42:52 p. m. GMT-6   
4    2023/06/27 7:42:56 p. m. GMT-6   
5    2023/06/27 7:42:57 p. m. GMT-6   
6    2023/06/27 7:42:57 p. m. GMT-6   
7    2023/06/27 7:43:04 p. m. GMT-6   
8    2023/06/27 7:43:10 p. m. GMT-6   
9    2023/06/27 7:43:12 p. m. GMT-6   
10   2023/06/27 7:43:12 p. m. GMT-6   
11   2023/06/27 7:43:16 p. m. GMT-6   
12   2023/06/27 7:43:16 p. m. GMT-6   
13   2023/06/27 7:43:29 p. m. GMT-6   
14   2023/06/27 7:43:34 p. m. GMT-6   
15   2023/06/27 7:43:50 p. m. GMT-6   
16   2023/06/27 7:44:01 p. m. GMT-6   
17   2023/06/27 7:44:01 p. m. GMT-6   
18   2023/06/27 7:44:12 p. m. GMT-6   
19   2023/06/27 7:44:14 p. m. GMT-6   
20   2023/06/27 7:44:17 p. m. GMT-6   
21   2023/06/27 7:44:20 p. m. GMT-6   
22   2023/06/27 7:44:25 p. m. GMT-6   
23   2023/06/27 7:44:30 p. m. GMT-6   
24   2023/06/27 7:44:31 p. m. GMT-6   
25   2023/06/27 7:45:04 p. m. GMT-6   
26   2023/06/27 7:45:37 p. m. GMT-6   
27   2023/06/27 7:45:45 p. m. GMT-6   
28   2023/06/27 7:46:10 p. m. GMT-6   
29   2023/06/27 7:46:14 p. m. GMT-6   
30   2023/06/27 7:46:28 p. m. GMT-6   
31   2023/06/27 7:46:32 p. m. GMT-6   
32   2023/06/27 7:46:37 p. m. GMT-6   
33   2023/06/27 7:49:23 p. m. GMT-6   
34   2023/06/27 7:51:23 p. m. GMT-6   
35   2023/06/27 7:55:00 p. m. GMT-6   
36   2023/06/27 8:05:42 p. m. GMT-6   
37   2023/06/27 8:22:29 p. m. GMT-6   
38  2023/06/27 10:02:11 p. m. GMT-6   
39  2023/06/27 10:31:28 p. m. GMT-6   
40  2023/06/28 10:12:04 p. m. GMT-6   
41   2023/06/29 2:00:51 a. m. GMT-6   
42   2023/07/03 1:55:24 p. m. GMT-6   

                          1.- ¿De dónde eres? 2.- ¿Cuántos años tienes?  \
0                                  Cd. Juárez             Entre 21 y 24   
1                        chihuahua, chihuahua             Entre 21 y 24   
2                         Chihuahua Chihuahua             Entre 18 y 20   
3                         Chihuahua Chihuahua             Entre 21 y 24   
4                            Chihuahua, Chih.                 Más de 30   
5                                      Puebla             Entre 21 y 24   
6                             Cd. Juarez Chih                 Más de 30   
7                               Ciudad Juarez             Entre 21 y 24   
8                              Aguascalientes             Entre 18 y 20   
9                            Cd Juarez, Chih.             Entre 21 y 24   
10                                     Juárez             Entre 21 y 24   
11                                 El Paso TX             Entre 18 y 20   
12                       Cuauhtemoc Chihuahua                 Más de 30   
13                                Cd. Juárez              Entre 21 y 24   
14                                    Hidalgo             Entre 25 y 29   
15                          Cd. Juarez, Chih.             Entre 21 y 24   
16                       Cd. Juarez Chihuahua                 Más de 30   
17             Ciudad Juarez Chihuahua Mexico             Entre 21 y 24   
18                              Ciudad Juarez                 Más de 30   
19                           Chihuahua, Chih.                 Más de 30   
20                              Ciudad Juarez             Entre 18 y 20   
21               Cd Juárez Chihuahua, México.                 Más de 30   
22                              Ciudad Juárez                 Más de 30   
23                                 Cd. Juárez             Entre 25 y 29   
24                                     Juarez             Entre 25 y 29   
25                     Cd. Juárez, Chihuahua              Entre 18 y 20   
26                            Aguascalientes              Entre 21 y 24   
27                                 Cd. Juarez             Entre 15 y 17   
28  San Francisco de los Romo, Aguascalientes             Entre 18 y 20   
29                                  Chihuahua         

In [44]:
#Manda llamar los primeros registros segun solicites
df.head(10)

Marca temporal   1.- ¿De dónde eres?  \
0  2023/06/27 7:42:12 p. m. GMT-6            Cd. Juárez   
1  2023/06/27 7:42:28 p. m. GMT-6  chihuahua, chihuahua   
2  2023/06/27 7:42:44 p. m. GMT-6   Chihuahua Chihuahua   
3  2023/06/27 7:42:52 p. m. GMT-6   Chihuahua Chihuahua   
4  2023/06/27 7:42:56 p. m. GMT-6      Chihuahua, Chih.   
5  2023/06/27 7:42:57 p. m. GMT-6                Puebla   
6  2023/06/27 7:42:57 p. m. GMT-6       Cd. Juarez Chih   
7  2023/06/27 7:43:04 p. m. GMT-6         Ciudad Juarez   
8  2023/06/27 7:43:10 p. m. GMT-6        Aguascalientes   
9  2023/06/27 7:43:12 p. m. GMT-6      Cd Juarez, Chih.   

  2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas?  \
0             Entre 21 y 24             Sí             No   
1             Entre 21 y 24             Sí             Sí   
2             Entre 18 y 20             Sí             Sí   
3             Entre 21 y 24             Sí             Sí   
4                 Más de 30             No             Sí   
5             Entre 21 y 24             Sí             Sí   
6                 Más de 30             No             Sí   
7             Entre 21 y 24             Sí             Sí   
8             Entre 18 y 20             Sí             No   
9             Entre 21 y 24             Sí             No   

  5.- ¿Cuál es tu nivel de conocimiento en Python?  \
0                                           Básico   
1                                           Básico   
2                                           Básico   
3                                           Básico   
4                                           Básico   
5                                           Básico   
6                                       Intermedio   
7                                           Básico   
8                                           Básico   
9                                           Básico   

  6.- ¿Qué tema relacionado con Python te gustaría aprender?  \
0                             Manejar bases de datos           
1                                    machine lerning           
2      Automatización y creación de apps/páginas web           
3                                  Análisis de datos           
4                              Conocer más librerias           
5                                APIS y data science           
6                                  Analisis de Datos           
7                                   Ciencia de datos           
8  Me gustaria aprender un poco de todo, pero mas...           
9  No tengo un tema en especifico, solo deseo rep...           

  7.- ¿Has participado en algún curso anteriormente en el IA Center?  \
0                                                 No                   
1                                                 Sí                   
2                                                 No                   
3                                                 Sí                   
4                                                 Sí                   
5                                                 No                   
6                                                 Sí                   
7                                                 Sí                   
8                                                 No                   
9                                                 Sí                   

                   8.- ¿Cuál es tu canción favorita?  
0                                           The Wolf  
1                                    eternity, anyma  
2                     Cornerstone- Arctic Monkeys :)  
3                                    Sea Gets Hotter  
4                         Love Me More, de Sam Smith  
5                           Fireflight - Unbreakable  
6                               Instrumental General  
7                          La bruja de Marco Flores   
8                                Canela-Nanpa Basico  
9  Depende del momento hy del día, ahora es Hielo...

In [43]:
#Manda llamar los ultimos registros segun solicites
df.tail(10)

Marca temporal                1.- ¿De dónde eres?  \
33   2023/06/27 7:49:23 p. m. GMT-6                      Ciudad Juárez   
34   2023/06/27 7:51:23 p. m. GMT-6                      Ciudad Juarez   
35   2023/06/27 7:55:00 p. m. GMT-6        Veracruz, estudio en Puebla   
36   2023/06/27 8:05:42 p. m. GMT-6                               CDMX   
37   2023/06/27 8:22:29 p. m. GMT-6                   Estado de Mexico   
38  2023/06/27 10:02:11 p. m. GMT-6                Ciudad Juarez, Chih   
39  2023/06/27 10:31:28 p. m. GMT-6                          cd juarez   
40  2023/06/28 10:12:04 p. m. GMT-6                          Chihuahua   
41   2023/06/29 2:00:51 a. m. GMT-6  Vivo en Ciudad Juárez. Soy cubana   
42   2023/07/03 1:55:24 p. m. GMT-6                      Ciudad Juarez   

   2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas?  \
33             Entre 18 y 20             Sí             No   
34             Entre 25 y 29             Sí             Sí   
35             Entre 25 y 29             Sí             No   
36             Entre 25 y 29             No             Sí   
37             Entre 21 y 24             Sí             Sí   
38             Entre 21 y 24             No             Sí   
39             Entre 21 y 24             Sí             Sí   
40             Entre 21 y 24             No             Sí   
41                 Más de 30             Sí             No   
42                 Más de 30             No             Sí   

   5.- ¿Cuál es tu nivel de conocimiento en Python?  \
33                                           Básico   
34                                       Intermedio   
35                                           Básico   
36                                           Básico   
37                                           Básico   
38                                           Básico   
39                                           Básico   
40                                           Básico   
41                                       Intermedio   
42                                       Intermedio   

   6.- ¿Qué tema relacionado con Python te gustaría aprender?  \
33                  Ciencia de Datos y automatización           
34                      ciencia de datos, webscraping           
35              Lo relacionado con análisis de datos.           
36                                       web scraping           
37                librerias, bloques paquetes etc....           
38                                  Analisis de datos           
39                                           punteros           
40                   Machine Learning y Deep Learning           
41  Cómo escribir un código de forma profesional, ...           
42                                     Automatizacion           

   7.- ¿Has participado en algún curso anteriormente en el IA Center?  \
33                                                 Sí                   
34                                                 Sí                   
35                                                 Sí                   
36                                                 No                   
37                                                 No                   
38                                                 Sí                   
39                                                 Sí                   
40                                                 Sí                   
41                                                 No                   
42                                                 No                   

                    8.- ¿Cuál es tu canción favorita?  
33       Cold Heart - PNAU REMIX Elton Jhon, Dua Lipa  
34                      Gorillaz - On Melancholy Hill  
35  En este momento Los Años Maravillosos de Littl...  
36                                        Young Turks  
37                            the weeknd- Out of time  
38                       https://youtu.be/BGVUiMskx_U  
39   

In [45]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 9 columns):
 #   Column                                                              Non-Null Count  Dtype 
---  ------                                                              --------------  ----- 
 0   Marca temporal                                                      43 non-null     object
 1   1.- ¿De dónde eres?                                                 43 non-null     object
 2   2.- ¿Cuántos años tienes?                                           43 non-null     object
 3   3.- ¿Estudias?                                                      43 non-null     object
 4   4.- ¿Trabajas?                                                      43 non-null     object
 5   5.- ¿Cuál es tu nivel de conocimiento en Python?                    43 non-null     object
 6   6.- ¿Qué tema relacionado con Python te gustaría aprender?          43 non-null     object
 7   7.- ¿Has participado en algún

## CSV

In [46]:
df = pd.read_csv("dataset/Perfil de estudiante.csv")
print(df.to_string())

                     Marca temporal                        1.- ¿De dónde eres? 2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas? 5.- ¿Cuál es tu nivel de conocimiento en Python?                                           6.- ¿Qué tema relacionado con Python te gustaría aprender? 7.- ¿Has participado en algún curso anteriormente en el IA Center?                             8.- ¿Cuál es tu canción favorita?
0    2023/06/27 7:42:12 p. m. GMT-6                                 Cd. Juárez             Entre 21 y 24             Sí             No                                           Básico                                                                               Manejar bases de datos                                                                 No                                                      The Wolf
1    2023/06/27 7:42:28 p. m. GMT-6                       chihuahua, chihuahua             Entre 21 y 24             Sí             Sí                                      

## JSON

In [47]:
df = pd.read_json("dataset/dataset.json")
print(df.to_string())

                                                 personas
0      {'nombre': 'Juan', 'edad': 25, 'ciudad': 'Madrid'}
1  {'nombre': 'María', 'edad': 30, 'ciudad': 'Barcelona'}
2   {'nombre': 'Pedro', 'edad': 35, 'ciudad': 'Valencia'}


## Limpieza de datos

In [61]:
data = {
    'Nombre': ['Juan', 'María', 'Pedro', 'Ana', 'Luis'],
    'Edad': [25, 32, None, 42, 28],
    'Fecha': ['31/01/2020', '31/01/2020', None, '31/01/2020', '01/31/2020'],
    'Género': ['M', 'F', None, 'F', 'M'],
    'Ciudad': ['Madrid', None, 'Madrid', 'Valencia', 'Barcelona'],
    'Altura': [175, 163, 180, 158, 170],
    'Peso': [70, None, 80, 60, 75],
    'Ingresos': [50000, 60000, 40000, None, 55000]
}

In [63]:
df = pd.DataFrame(data)
print(df)

#Nan hace referencia que el dato no es un numero

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [50]:
# Eliminar toda la fila cuando hay campos vacios pero se asignan a un nuevo dataframe dejando intacto el original
df_sin_vacios = df.dropna()
print(df_sin_vacios.to_string())

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [51]:

# Borra las filas que tenga vacias dento del dataframe original
df.dropna(inplace=True)
print(df.to_string)

<bound method DataFrame.to_string of   Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0>


In [54]:
df

Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0

In [57]:
# Cambiar los registros null por un registro valido

df_relleno = df.fillna("Sin registro")
print(df_relleno.to_string())

  Nombre          Edad         Fecha        Género        Ciudad  Altura          Peso      Ingresos
0   Juan          25.0    31/01/2020             M        Madrid     175          70.0       50000.0
1  María          32.0    31/01/2020             F  Sin registro     163  Sin registro       60000.0
2  Pedro  Sin registro  Sin registro  Sin registro        Madrid     180          80.0       40000.0
3    Ana          42.0    31/01/2020             F      Valencia     158          60.0  Sin registro
4   Luis          28.0    01/31/2020             M     Barcelona     170          75.0       55000.0


In [64]:
#Rellenar registros null con un Cero para no perjudicar el tipo de campo
df_cero = df["Ingresos"].fillna(0)

print(df_cero)

0    50000.0
1    60000.0
2    40000.0
3        0.0
4    55000.0
Name: Ingresos, dtype: float64


In [65]:
media = df["Ingresos"].mean()
print(media)

51250.0


In [67]:

#Se asigna la media a los valores null
df_media = df["Ingresos"].fillna(media)
print(df_media)

0    50000.0
1    60000.0
2    40000.0
3    51250.0
4    55000.0
Name: Ingresos, dtype: float64


In [68]:
mediana = df["Ingresos"].median()
print(mediana)

#Se asigna la mediana a los valores null
df_mediana = df["Ingresos"].fillna(mediana)
print(df_mediana)

52500.0
0    50000.0
1    60000.0
2    40000.0
3    52500.0
4    55000.0
Name: Ingresos, dtype: float64


In [69]:
moda = df["Ingresos"].mode()
print(moda)

#Se asigna la moda a los valores null
df_moda = df["Ingresos"].fillna(moda)
print(df_moda)

0    40000.0
1    50000.0
2    55000.0
3    60000.0
Name: Ingresos, dtype: float64
0    50000.0
1    60000.0
2    40000.0
3    60000.0
4    55000.0
Name: Ingresos, dtype: float64


In [70]:
df.loc[1, "Peso"] = 70
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163  70.0   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [71]:
# Devuelve True o False si hay datos duplicados
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [72]:
#inplace se utiliza para hacer los cambios directamente en el dataframe

df.drop_duplicates(inplace=True)

In [75]:

# Busca la correlacion de una columna con otra
data2 ={
    'A' : [1,2,3,4,5],
    'B' : [5,4,3,2,1],
    'C' : [2,4,6,8,10]
    
}
df2 = pd.DataFrame(data2)
print(df2)
df2.corr()


   A  B   C
0  1  5   2
1  2  4   4
2  3  3   6
3  4  2   8
4  5  1  10


A    B    C
A  1.0 -1.0  1.0
B -1.0  1.0 -1.0
C  1.0 -1.0  1.0